import {
  type InvestmentResult,
  sortInvestmentResultsByDate,
} from "./scheduleFAExport";

const accountStartDate = "2000-01-01";

/** Creates balanced RSU vesting transactions from investments with known USD cost. */
export function generateBeancount(data: InvestmentResult[]): string {
  const exportable = data.filter(hasInitialValue);
  const symbols = [
    ...new Set(exportable.map((item) => commodity(item.equity))),
  ].sort();
  const lines = [
    "; Generated by Schedule FA Generator. Review account names and values before importing.",
    'option "operating_currency" "USD"',
    "",
    ...symbols.flatMap((symbol) => [
      `${accountStartDate} open Assets:Investments:US:${symbol} ${symbol}`,
    ]),
    `${accountStartDate} open Income:Employment:RSU USD`,
    "",
  ];

  for (const item of sortInvestmentResultsByDate(exportable).reverse()) {
    const symbol = commodity(item.equity);
    const unitPrice = item.initialValueUSD / item.units;
    lines.push(
      `${item.dateOfInvestment} * "RSU vesting - ${symbol}"`,
      `  Assets:Investments:US:${symbol} ${formatNumber(item.units)} ${symbol} {${formatNumber(unitPrice)} USD}`,
      `  Income:Employment:RSU -${formatNumber(item.initialValueUSD)} USD`,
      "",
    );
  }

  for (const item of data.filter(
    (item) => item.initialValueUSD === undefined,
  )) {
    lines.push(
      `; Skipped ${item.equity} vesting on ${item.dateOfInvestment}: initial USD value is unavailable.`,
    );
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function hasInitialValue(
  item: InvestmentResult,
): item is InvestmentResult & { initialValueUSD: number } {
  return (
    item.initialValueUSD !== undefined &&
    Number.isFinite(item.initialValueUSD) &&
    item.initialValueUSD >= 0
  );
}

function commodity(equity: string): string {
  return equity.replace(/[^A-Za-z0-9]/g, "").toUpperCase() || "STOCK";
}

function formatNumber(value: number): string {
  return value.toFixed(8).replace(/\.?(0+)$/, "");
}
